version: 2.1

orbs:
  kitchen: sous-chefs/kitchen@1.0.0

workflows:
  kitchen:
    jobs:
      - kitchen/danger:
          name: danger
          context: Danger
      - kitchen/lint:
          name: lint
      - kitchen/dokken-single:
          suite: default
          name: default-ubuntu-1604
          platform: ubuntu-1604
          requires: [lint, danger]
      - kitchen/dokken-single:
          suite: default
          name: default-ubuntu-1804
          platform: ubuntu-1804
          requires: [lint, danger]
      - kitchen/dokken-single:
          suite: default
          name: default-debian-8
          platform: debian-8
          requires: [lint, danger]
      - kitchen/dokken-single:
          suite: default
          name: default-debian-9
          platform: debian-9
          requires: [lint, danger]
